# Generated by Django 4.2.4 on 2023-12-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delay_reporting', '0007_alter_order_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delayreport',
            name='delay_minutes',
        ),
    ]
