# Generated by Django 4.2.4 on 2023-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delay_reporting', '0008_remove_delayreport_delay_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='delayreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
