# Generated by Django 4.2.4 on 2023-12-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='order',
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'Delivered'), ('PICKED', 'Picked'), ('AT_VENDOR', 'Vendor At'), ('ASSIGNED', 'Assigned')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
